/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGUI;

import controlador.ClienteCt;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author fabih
 */
public class ConsultarSaldo extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarSaldo
     */
    public ConsultarSaldo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ClienteCt clienteCuentas = new ClienteCt();
        ArrayList<Integer> cuentas = clienteCuentas.numCuentas();
        for (int i = 0; i < cuentas.size(); i++){
            cbNumeroCuenta.addItem(String.valueOf(cuentas.get(i)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linea = new javax.swing.JLabel();
        btConsultar = new javax.swing.JButton();
        back = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        cbDivisa = new javax.swing.JComboBox<>();
        cbNumeroCuenta = new javax.swing.JComboBox<>();
        nombre1 = new javax.swing.JLabel();
        txtPin = new javax.swing.JPasswordField();
        nombre2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 51));
        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("CONSULTAR SALDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -10, 320, 90));

        linea.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        linea.setForeground(new java.awt.Color(0, 0, 102));
        linea.setText("______________________________");
        getContentPane().add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 580, 50));

        btConsultar.setBackground(new java.awt.Color(0, 0, 102));
        btConsultar.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        btConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btConsultar.setText("CONSULTAR");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 160, 40));

        back.setBackground(new java.awt.Color(0, 102, 51));
        back.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 30));

        nombre.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre.setText("PIN");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        cbDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Dolares", "Colones" }));
        cbDivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDivisaActionPerformed(evt);
            }
        });
        getContentPane().add(cbDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 210, 30));

        cbNumeroCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        getContentPane().add(cbNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 450, 30));

        nombre1.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre1.setText("Seleccione el número de cuenta");
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));
        getContentPane().add(txtPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 30));

        nombre2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre2.setText("Divisa");
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:
        ClienteCt cliente = new ClienteCt();
        String numCuenta = cbNumeroCuenta.getSelectedItem().toString();
        String tipoDivisa = cbDivisa.getSelectedItem().toString();
        String pin = txtPin.getText();
        
        if (tipoDivisa.equals("Colones")){
            JOptionPane.showMessageDialog(null,cliente.consultarSaldoCuentaColones(numCuenta,pin));   
        }
        if (tipoDivisa.equals("Dolares")){
            JOptionPane.showMessageDialog(null,cliente.consultarSaldoCuentaDolares(numCuenta,pin));
        }
        
    }//GEN-LAST:event_btConsultarActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MenuConsultas abrir = new MenuConsultas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void cbDivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDivisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDivisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btConsultar;
    private javax.swing.JComboBox<String> cbDivisa;
    private javax.swing.JComboBox<String> cbNumeroCuenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel linea;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JPasswordField txtPin;
    // End of variables declaration//GEN-END:variables
}
