/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGUI;

import controlador.ActualizacionDatos;
import controlador.ClienteCt;

/**
 *
 * @author fabih
 */
public class MenuConsultas extends javax.swing.JFrame {

    /**
     * Creates new form MenuConsultas
     */
    public MenuConsultas() {
        ActualizacionDatos.refrescarPrograma();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linea = new javax.swing.JLabel();
        btConsultarCliente = new javax.swing.JButton();
        btConsultarCuenta = new javax.swing.JButton();
        btConsultarSaldo = new javax.swing.JButton();
        btConsultarStatus = new javax.swing.JButton();
        back = new javax.swing.JButton();
        btConsultarTipoCambio = new javax.swing.JButton();
        btConsultarEstadoCuenta = new javax.swing.JButton();
        btConsultarGananciaCuenta = new javax.swing.JButton();
        btConsultarGananciaTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 51));
        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("MENÚ DE CONSULTAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 380, 90));

        linea.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        linea.setForeground(new java.awt.Color(0, 0, 102));
        linea.setText("_________________________________________");
        getContentPane().add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 780, 50));

        btConsultarCliente.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarCliente.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btConsultarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarCliente.setText("CONSULTAR CLIENTE");
        btConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 320, 50));

        btConsultarCuenta.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarCuenta.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btConsultarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarCuenta.setText("CONSULTAR CUENTA");
        btConsultarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 320, 50));

        btConsultarSaldo.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarSaldo.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btConsultarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarSaldo.setText("CONSULTAR SALDO");
        btConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 320, 50));

        btConsultarStatus.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarStatus.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btConsultarStatus.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarStatus.setText("CONSULTAR STATUS");
        btConsultarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 320, 50));

        back.setBackground(new java.awt.Color(0, 102, 51));
        back.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 130, 30));

        btConsultarTipoCambio.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarTipoCambio.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btConsultarTipoCambio.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarTipoCambio.setText("CONSULTAR TIPO DE CAMBIO");
        btConsultarTipoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarTipoCambioActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarTipoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 320, 50));

        btConsultarEstadoCuenta.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarEstadoCuenta.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btConsultarEstadoCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarEstadoCuenta.setText("CONSULTAR ESTADO DE CUENTA");
        btConsultarEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarEstadoCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarEstadoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 50));

        btConsultarGananciaCuenta.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarGananciaCuenta.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btConsultarGananciaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarGananciaCuenta.setText("CONSULTAR GANANCIA POR CUENTA");
        btConsultarGananciaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarGananciaCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarGananciaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 320, 50));

        btConsultarGananciaTotal.setBackground(new java.awt.Color(0, 0, 102));
        btConsultarGananciaTotal.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        btConsultarGananciaTotal.setForeground(new java.awt.Color(255, 255, 255));
        btConsultarGananciaTotal.setText("CONSULTAR GANANCIA TOTAL");
        btConsultarGananciaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarGananciaTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultarGananciaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 320, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarClienteActionPerformed
        ListarClientesOrdenados abrir = new ListarClientesOrdenados();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarClienteActionPerformed

    private void btConsultarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarCuentaActionPerformed
        ListarCuentasOrdenadas abrir = new ListarCuentasOrdenadas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarCuentaActionPerformed

    private void btConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSaldoActionPerformed
        ConsultarSaldo abrir = new ConsultarSaldo();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarSaldoActionPerformed

    private void btConsultarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarStatusActionPerformed
        ConsultarStatus abrir = new ConsultarStatus();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarStatusActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MenuPrincipal abrir = new MenuPrincipal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void btConsultarTipoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarTipoCambioActionPerformed
        ConsultarTipoCambio abrir = new ConsultarTipoCambio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarTipoCambioActionPerformed

    private void btConsultarEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarEstadoCuentaActionPerformed
        ConsultarEstadoCuenta abrir = new ConsultarEstadoCuenta();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarEstadoCuentaActionPerformed

    private void btConsultarGananciaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarGananciaCuentaActionPerformed
        ConsultarGananciasPorCuenta abrir = new ConsultarGananciasPorCuenta();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarGananciaCuentaActionPerformed

    private void btConsultarGananciaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarGananciaTotalActionPerformed
        ConsultarGananciasTotales abrir = new ConsultarGananciasTotales();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btConsultarGananciaTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btConsultarCliente;
    private javax.swing.JButton btConsultarCuenta;
    private javax.swing.JButton btConsultarEstadoCuenta;
    private javax.swing.JButton btConsultarGananciaCuenta;
    private javax.swing.JButton btConsultarGananciaTotal;
    private javax.swing.JButton btConsultarSaldo;
    private javax.swing.JButton btConsultarStatus;
    private javax.swing.JButton btConsultarTipoCambio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel linea;
    // End of variables declaration//GEN-END:variables
}
