
package vistaGUI;

import controlador.ActualizacionDatos;
import controlador.ClienteCt;
public class MenuOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuOperaciones
     */
    public MenuOperaciones() {
        initComponents();
        ActualizacionDatos.refrescarPrograma();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linea = new javax.swing.JLabel();
        btDepositar = new javax.swing.JButton();
        btRetirar = new javax.swing.JButton();
        btTransferencia = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 51));
        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("MENÚ DE OPERACIONES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 420, 90));

        linea.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        linea.setForeground(new java.awt.Color(0, 0, 102));
        linea.setText("_________________________________________");
        getContentPane().add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 780, 50));

        btDepositar.setBackground(new java.awt.Color(0, 0, 102));
        btDepositar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btDepositar.setForeground(new java.awt.Color(255, 255, 255));
        btDepositar.setText("DEPOSITAR DINERO");
        btDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositarActionPerformed(evt);
            }
        });
        getContentPane().add(btDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 320, 50));

        btRetirar.setBackground(new java.awt.Color(0, 0, 102));
        btRetirar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btRetirar.setText("RETIRAR DINERO");
        btRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 320, 50));

        btTransferencia.setBackground(new java.awt.Color(0, 0, 102));
        btTransferencia.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        btTransferencia.setText("REALIZAR TRANSFERENCIA BANCARIA");
        btTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 670, 50));

        back.setBackground(new java.awt.Color(0, 102, 51));
        back.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositarActionPerformed
        Depositar abrir = new Depositar();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btDepositarActionPerformed

    private void btRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarActionPerformed
        Retirar abrir = new Retirar();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRetirarActionPerformed

    private void btTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferenciaActionPerformed
        Transferir abrir = new Transferir();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btTransferenciaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MenuPrincipal abrir = new MenuPrincipal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btDepositar;
    private javax.swing.JButton btRetirar;
    private javax.swing.JButton btTransferencia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel linea;
    // End of variables declaration//GEN-END:variables
}
