/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGUI;

import controlador.ClienteCt;
import controlador.CuentaBancariaCt;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author fabih
 */
public class Retirar extends javax.swing.JFrame {
    private String pPalabra;
    
    public Retirar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ClienteCt clienteCuentas = new ClienteCt();
        ArrayList<Integer> cuentas = clienteCuentas.numCuentas();
        for (int i = 0; i < cuentas.size(); i++){
            cbNumeroCuenta.addItem(String.valueOf(cuentas.get(i)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linea = new javax.swing.JLabel();
        btRetirar = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        cbDivisa = new javax.swing.JComboBox<>();
        cbNumeroCuenta = new javax.swing.JComboBox<>();
        nombre1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btBack = new javax.swing.JButton();
        nombre3 = new javax.swing.JLabel();
        txtPin = new javax.swing.JPasswordField();
        btMensaje = new javax.swing.JButton();
        txtPalabra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 51));
        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("RETIRAR DINERO DE CUENTA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -10, 460, 90));

        linea.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        linea.setForeground(new java.awt.Color(0, 0, 102));
        linea.setText("_______________________________");
        getContentPane().add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 600, 50));

        btRetirar.setBackground(new java.awt.Color(0, 0, 102));
        btRetirar.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        btRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btRetirar.setText("RETIRAR");
        btRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarActionPerformed(evt);
            }
        });
        getContentPane().add(btRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 160, 40));

        nombre.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre.setText("Monto");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        cbDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Dolares", "Colones" }));
        cbDivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDivisaActionPerformed(evt);
            }
        });
        getContentPane().add(cbDivisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, 30));

        cbNumeroCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        getContentPane().add(cbNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 30));

        nombre1.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre1.setText("Número de Cuenta del retiro");
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        nombre2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre2.setText("Divisa");
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 220, 30));

        btBack.setBackground(new java.awt.Color(0, 102, 51));
        btBack.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 255, 255));
        btBack.setText("BACK");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 80, 30));

        nombre3.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre3.setText("PIN");
        getContentPane().add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));
        getContentPane().add(txtPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 220, 30));

        btMensaje.setBackground(new java.awt.Color(0, 102, 51));
        btMensaje.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btMensaje.setForeground(new java.awt.Color(255, 255, 255));
        btMensaje.setText("SMS");
        btMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMensajeActionPerformed(evt);
            }
        });
        getContentPane().add(btMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 80, 30));
        getContentPane().add(txtPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 220, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarActionPerformed
       ClienteCt cliente = new ClienteCt();
       if(cbDivisa.getSelectedItem().toString().equals("Colones")){
            JOptionPane.showMessageDialog(null,cliente.realizarRetiroColones(cbNumeroCuenta.getSelectedItem().toString(), txtMonto.getText(), txtPalabra.getText(), pPalabra));
       }
       if(cbDivisa.getSelectedItem().toString().equals("Dolares")){
            JOptionPane.showMessageDialog(null,cliente.realizarRetiroDolares(cbNumeroCuenta.getSelectedItem().toString(), txtMonto.getText(), txtPalabra.getText(), pPalabra));
       }
    }//GEN-LAST:event_btRetirarActionPerformed

    private void cbDivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDivisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDivisaActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        MenuOperaciones abrir = new MenuOperaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btBackActionPerformed

    private void btMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMensajeActionPerformed
       ClienteCt cliente = new ClienteCt();
       pPalabra = cliente.realizarRetiroColonesAux(cbNumeroCuenta.getSelectedItem().toString(),txtPin.getText());
       JOptionPane.showMessageDialog(null,"Mensaje enviado al telefono vinculado a su cuenta.");
    }//GEN-LAST:event_btMensajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retirar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btMensaje;
    private javax.swing.JButton btRetirar;
    private javax.swing.JComboBox<String> cbDivisa;
    private javax.swing.JComboBox<String> cbNumeroCuenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel linea;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JPasswordField txtPin;
    // End of variables declaration//GEN-END:variables
}
