/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaGUI;

import controlador.ClienteCt;
import  controlador.ClienteCt;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author fabih
 */
public class Transferir extends javax.swing.JFrame {

    /**
     * Creates new form Transferir
     */
    public Transferir() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ClienteCt clienteCuentas = new ClienteCt();
        ArrayList<Integer> cuentas = clienteCuentas.numCuentas();
        for (int i = 0; i < cuentas.size(); i++){
            cbNumeroCuentaOrigen.addItem(String.valueOf(cuentas.get(i)));
            cbNumeroCuentaDestino.addItem(String.valueOf(cuentas.get(i)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linea = new javax.swing.JLabel();
        btTransferir = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        cbNumeroCuentaDestino = new javax.swing.JComboBox<>();
        nombre1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        txtPin = new javax.swing.JPasswordField();
        cbNumeroCuentaOrigen = new javax.swing.JComboBox<>();
        nombre4 = new javax.swing.JLabel();
        txtPalabraClave = new javax.swing.JTextField();
        nombre3 = new javax.swing.JLabel();
        pinActual1 = new javax.swing.JLabel();
        btSMS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 51));
        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("TRANSFERIR DINERO A CUENTA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 510, 90));

        linea.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        linea.setForeground(new java.awt.Color(0, 0, 102));
        linea.setText("_______________________________");
        getContentPane().add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 600, 50));

        btTransferir.setBackground(new java.awt.Color(0, 0, 102));
        btTransferir.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        btTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btTransferir.setText("TRANFERIR");
        btTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferirActionPerformed(evt);
            }
        });
        getContentPane().add(btTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 160, 40));

        nombre.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre.setText("Palabra Clave");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        cbNumeroCuentaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        getContentPane().add(cbNumeroCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 220, 30));

        nombre1.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre1.setText("Número de Cuenta Destino");
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        nombre2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre2.setText("Monto a transferir");
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 190, 30));

        back.setBackground(new java.awt.Color(0, 102, 51));
        back.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 120, 30));

        txtPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinActionPerformed(evt);
            }
        });
        getContentPane().add(txtPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, 30));

        cbNumeroCuentaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        getContentPane().add(cbNumeroCuentaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 30));

        nombre4.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre4.setText("Número de Cuenta Origen");
        getContentPane().add(nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        getContentPane().add(txtPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 220, 30));

        nombre3.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        nombre3.setText("PIN");
        getContentPane().add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        pinActual1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        pinActual1.setText("¢");
        getContentPane().add(pinActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btSMS.setBackground(new java.awt.Color(0, 0, 102));
        btSMS.setFont(new java.awt.Font("Nirmala UI", 1, 17)); // NOI18N
        btSMS.setForeground(new java.awt.Color(255, 255, 255));
        btSMS.setText("SMS");
        btSMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSMSActionPerformed(evt);
            }
        });
        getContentPane().add(btSMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferirActionPerformed
        // TODO add your handling code here:
        String numCuentaOrigen = cbNumeroCuentaOrigen.getSelectedItem().toString();
        String numCuentaDestino = cbNumeroCuentaDestino.getSelectedItem().toString();
        String pin = txtPin.getText();
        String monto = txtMonto.getText();
        String palabraClave = txtPalabraClave.getText();
         ClienteCt cliente = new ClienteCt();
        JOptionPane.showMessageDialog(null,cliente.realizarTransferencia(numCuentaOrigen,numCuentaDestino,monto,pin,palabraClave));
    }//GEN-LAST:event_btTransferirActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MenuOperaciones abrir = new MenuOperaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void txtPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinActionPerformed
        // TODO add your handling code here:
        String numCuenta = cbNumeroCuentaOrigen.getSelectedItem().toString();
        String pin = txtPin.getText();
    }//GEN-LAST:event_txtPinActionPerformed

    private void btSMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSMSActionPerformed
        String numCuentaOrigen = cbNumeroCuentaOrigen.getSelectedItem().toString();
        String pin = txtPin.getText();
        ClienteCt cliente = new ClienteCt();
        JOptionPane.showMessageDialog(null,cliente.realizarTransferenciaAux(numCuentaOrigen,pin));  
    }//GEN-LAST:event_btSMSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btSMS;
    private javax.swing.JButton btTransferir;
    private javax.swing.JComboBox<String> cbNumeroCuentaDestino;
    private javax.swing.JComboBox<String> cbNumeroCuentaOrigen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel linea;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombre4;
    private javax.swing.JLabel pinActual1;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtPalabraClave;
    private javax.swing.JPasswordField txtPin;
    // End of variables declaration//GEN-END:variables
}
